# 基于官方 MobSF 构建的定制版本

FROM opensecurity/mobile-security-framework-mobsf:latest

LABEL maintainer="pansinliu <pansinliu@gmail.com>"
LABEL description="MobSF - Mobile Security Framework for Android/iOS security testing"

# 暴露端口
EXPOSE 8000

# 使用官方推荐的启动方式
# 不要使用 runserver，使用生产级服务器
